// Auto-generated from 컬러테이블.xlsx
export const colorData = [
  {
    "id": 1,
    "code": "R/vv",
    "nameKo": "선명한 빨강",
    "nameEn": "vivid Red",
    "munsell": "5R 4/14",
    "l": 44.42,
    "a": 49.79,
    "b": 22.84,
    "commonKo": "빨강",
    "commonEn": "Red"
  },
  {
    "id": 2,
    "code": "YR/vv",
    "nameKo": "선명한 주황",
    "nameEn": "vivid Yellow Red",
    "munsell": "5YR 7/14",
    "l": 70.7,
    "a": 24.87,
    "b": 31.97,
    "commonKo": "주황",
    "commonEn": "Orange"
  },
  {
    "id": 3,
    "code": "Y/vv",
    "nameKo": "선명한 노랑",
    "nameEn": "vivid Yellow",
    "munsell": "5Y 8.5/14",
    "l": 82.97,
    "a": 6.33,
    "b": 83.86,
    "commonKo": "노랑",
    "commonEn": "Yellow"
  },
  {
    "id": 4,
    "code": "GY/vv",
    "nameKo": "선명한 연두",
    "nameEn": "vivid Green Yellow",
    "munsell": "5GY 7/12",
    "l": 71.53,
    "a": -20.02,
    "b": 61.61,
    "commonKo": "연두",
    "commonEn": "Green Yellow"
  },
  {
    "id": 5,
    "code": "G/vv",
    "nameKo": "선명한 초록",
    "nameEn": "vivid Green",
    "munsell": "5G 5/10",
    "l": 55.06,
    "a": -43.3,
    "b": 15.97,
    "commonKo": "녹색",
    "commonEn": "Green"
  },
  {
    "id": 6,
    "code": "BG/vv",
    "nameKo": "선명한 청록",
    "nameEn": "vivid Blue Green",
    "munsell": "5BG 5/10",
    "l": 55.99,
    "a": -38.58,
    "b": -13.2,
    "commonKo": "청록색",
    "commonEn": "Blue Green"
  },
  {
    "id": 7,
    "code": "B/vv",
    "nameKo": "선명한 파랑",
    "nameEn": "vivid Blue",
    "munsell": "5B 4/10",
    "l": 49.45,
    "a": -38.82,
    "b": -24.75,
    "commonKo": "파랑",
    "commonEn": "Blue"
  },
  {
    "id": 8,
    "code": "PB/vv",
    "nameKo": "선명한 남색",
    "nameEn": "vivid Purple Blue",
    "munsell": "5PB 5/12",
    "l": 57.57,
    "a": -7.54,
    "b": -32.27,
    "commonKo": "남색",
    "commonEn": "Cobalt Blue"
  },
  {
    "id": 9,
    "code": "P/vv",
    "nameKo": "선명한 보라",
    "nameEn": "vivid Purple",
    "munsell": "5P 4/12",
    "l": 47.59,
    "a": 25.53,
    "b": -29.51,
    "commonKo": "보라",
    "commonEn": "Purple"
  },
  {
    "id": 10,
    "code": "RP/vv",
    "nameKo": "선명한 자주",
    "nameEn": "vivid Red Purple",
    "munsell": "5RP 4/12",
    "l": 45.97,
    "a": 39.33,
    "b": -4.83,
    "commonKo": "자주",
    "commonEn": "Reddish Purple"
  },
  {
    "id": 11,
    "code": "R/◎",
    "nameKo": "빨강",
    "nameEn": "Red",
    "munsell": "5R 4/12",
    "l": 50.39,
    "a": 39.43,
    "b": 14.76,
    "commonKo": "양홍색",
    "commonEn": "Carmine"
  },
  {
    "id": 12,
    "code": "YR/◎",
    "nameKo": "주황",
    "nameEn": "Yellow Red",
    "munsell": "5YR 6/14",
    "l": 60.96,
    "a": 36.21,
    "b": 53.24,
    "commonKo": "주황",
    "commonEn": "Orange"
  },
  {
    "id": 13,
    "code": "Y/◎",
    "nameKo": "노랑",
    "nameEn": "Yellow",
    "munsell": "5Y 8/12",
    "l": 70.58,
    "a": 5.4,
    "b": 73.37,
    "commonKo": "카나리아색",
    "commonEn": "Canary Yellow"
  },
  {
    "id": 14,
    "code": "GY/◎",
    "nameKo": "연두",
    "nameEn": "Green Yellow",
    "munsell": "5GY 6/10",
    "l": 61.93,
    "a": -16.13,
    "b": 49.71,
    "commonKo": "목초색",
    "commonEn": "Meadow Green"
  },
  {
    "id": 15,
    "code": "G/◎",
    "nameKo": "초록",
    "nameEn": "Green",
    "munsell": "5G 4/8",
    "l": 47.29,
    "a": -35.08,
    "b": -4.33,
    "commonKo": "에메랄드그린",
    "commonEn": "Emerald Green"
  },
  {
    "id": 16,
    "code": "BG/◎",
    "nameKo": "청록",
    "nameEn": "Blue Green",
    "munsell": "5BG 4/8",
    "l": 43.53,
    "a": -29.6,
    "b": -3.12,
    "commonKo": "공작녹색",
    "commonEn": "Peacock Green"
  },
  {
    "id": 17,
    "code": "B/◎",
    "nameKo": "파랑",
    "nameEn": "Blue",
    "munsell": "5B 4/10",
    "l": 49.99,
    "a": -32.57,
    "b": -29.81,
    "commonKo": "세룰리언블루",
    "commonEn": "Cerulean Blue"
  },
  {
    "id": 18,
    "code": "PB/◎",
    "nameKo": "남색",
    "nameEn": "Purple Blue",
    "munsell": "5PB 4/12",
    "l": 48.08,
    "a": -6.56,
    "b": -38.48,
    "commonKo": "코발트블루",
    "commonEn": "Cobalt Blue"
  },
  {
    "id": 19,
    "code": "P/◎",
    "nameKo": "보라",
    "nameEn": "Purple",
    "munsell": "5P 4/10",
    "l": 38.7,
    "a": 25.1,
    "b": -21.92,
    "commonKo": "로얄퍼플",
    "commonEn": "Royal Purple"
  },
  {
    "id": 20,
    "code": "RP/◎",
    "nameKo": "자주",
    "nameEn": "Red Purple",
    "munsell": "5RP 3/10",
    "l": 37.78,
    "a": 32.4,
    "b": -7.67,
    "commonKo": "붉은보라",
    "commonEn": "Red Purple"
  },
  {
    "id": 21,
    "code": "R/dp",
    "nameKo": "진한 빨강",
    "nameEn": "deep Red",
    "munsell": "5R 4/6",
    "l": 49.66,
    "a": 19.97,
    "b": 10.4,
    "commonKo": "팥색",
    "commonEn": "Red Bean"
  },
  {
    "id": 22,
    "code": "YR/dp",
    "nameKo": "진한 주황",
    "nameEn": "deep Yellow Red",
    "munsell": "5YR 4/6",
    "l": 44.87,
    "a": 20.26,
    "b": 22.17,
    "commonKo": "떡갈나무색",
    "commonEn": "Oak Tree"
  },
  {
    "id": 23,
    "code": "Y/dp",
    "nameKo": "진한 노랑",
    "nameEn": "deep Yellow",
    "munsell": "5Y 4/6",
    "l": 44.97,
    "a": -10.2,
    "b": 29.6,
    "commonKo": "다시마색",
    "commonEn": "Tangle"
  },
  {
    "id": 24,
    "code": "GY/dp",
    "nameKo": "진한 연두",
    "nameEn": "deep Green Yellow",
    "munsell": "5GY 4/6",
    "l": 44.98,
    "a": -10.2,
    "b": 29.6,
    "commonKo": "이끼색",
    "commonEn": "Moss Green"
  },
  {
    "id": 25,
    "code": "G/dp",
    "nameKo": "진한 초록",
    "nameEn": "deep Green",
    "munsell": "5G 4/6",
    "l": 45.98,
    "a": -24.79,
    "b": 9.63,
    "commonKo": "비리디언",
    "commonEn": "Viridian"
  },
  {
    "id": 26,
    "code": "BG/dp",
    "nameKo": "진한 청록",
    "nameEn": "deep Blue Green",
    "munsell": "5BG 4/6",
    "l": 46.23,
    "a": -26.14,
    "b": -2.61,
    "commonKo": "공작녹색",
    "commonEn": "Peacock Green"
  },
  {
    "id": 27,
    "code": "B/dp",
    "nameKo": "진한 파랑",
    "nameEn": "deep Blue",
    "munsell": "5B 4/6",
    "l": 47.05,
    "a": -17.62,
    "b": -15.98,
    "commonKo": "청동색",
    "commonEn": "Bronze Blue"
  },
  {
    "id": 28,
    "code": "PB/dp",
    "nameKo": "진한 남색",
    "nameEn": "deep Purple Blue",
    "munsell": "5PB 4/6",
    "l": 47.21,
    "a": -2.49,
    "b": -2.89,
    "commonKo": "오리엔트블루",
    "commonEn": "Orient Blue"
  },
  {
    "id": 29,
    "code": "P/dp",
    "nameKo": "진한 보라",
    "nameEn": "deep Purple",
    "munsell": "5P 4/6",
    "l": 46.19,
    "a": 11.9,
    "b": -15.64,
    "commonKo": "포도색",
    "commonEn": "Grape"
  },
  {
    "id": 30,
    "code": "RP/dp",
    "nameKo": "진한 자주",
    "nameEn": "deep Red Purple",
    "munsell": "5RP 4/6",
    "l": 44.97,
    "a": 21.88,
    "b": -3.84,
    "commonKo": "다알리아색",
    "commonEn": "Dahlia Purple"
  },
  {
    "id": 31,
    "code": "R/dk",
    "nameKo": "어두운 빨강",
    "nameEn": "dark Red",
    "munsell": "5R 3/6",
    "l": 36.92,
    "a": 22.19,
    "b": 8.06,
    "commonKo": "건포도색",
    "commonEn": "Raisins"
  },
  {
    "id": 32,
    "code": "YR/dk",
    "nameKo": "어두운 주황",
    "nameEn": "dark Yellow Red",
    "munsell": "5YR 3/6",
    "l": 37.04,
    "a": 16.76,
    "b": 17.67,
    "commonKo": "코코아색",
    "commonEn": "Cocoa"
  },
  {
    "id": 33,
    "code": "Y/dk",
    "nameKo": "어두운 노랑",
    "nameEn": "dark Yellow",
    "munsell": "5Y 3/4",
    "l": 36.75,
    "a": 2.6,
    "b": 14.91,
    "commonKo": "브라운올리브",
    "commonEn": "Brown Olive"
  },
  {
    "id": 34,
    "code": "GY/dk",
    "nameKo": "어두운 연두",
    "nameEn": "dark Green Yellow",
    "munsell": "5GY 3/4",
    "l": 36.9,
    "a": -6.8,
    "b": 12.16,
    "commonKo": "올리브그린",
    "commonEn": "Olive Green"
  },
  {
    "id": 35,
    "code": "G/dk",
    "nameKo": "어두운 초록",
    "nameEn": "dark Green",
    "munsell": "5G 2/6",
    "l": 31.04,
    "a": -12.88,
    "b": 4.42,
    "commonKo": "오이색",
    "commonEn": "Cucumber Green"
  },
  {
    "id": 36,
    "code": "BG/dk",
    "nameKo": "어두운 청록",
    "nameEn": "dark Blue Green",
    "munsell": "5BG 2/6",
    "l": 31.66,
    "a": -16.98,
    "b": -2.67,
    "commonKo": "북청색",
    "commonEn": "Prussian Green"
  },
  {
    "id": 37,
    "code": "B/dk",
    "nameKo": "어두운 파랑",
    "nameEn": "dark Blue",
    "munsell": "5B 2/6",
    "l": 32.3,
    "a": -13.06,
    "b": -11.92,
    "commonKo": "심해색",
    "commonEn": "Marine Blue"
  },
  {
    "id": 38,
    "code": "PB/dk",
    "nameKo": "어두운 남색",
    "nameEn": "dark Purple Blue",
    "munsell": "5PB 2/6",
    "l": 32.26,
    "a": -1.75,
    "b": -17.94,
    "commonKo": "남색(쪽색)",
    "commonEn": "Bluish Violet"
  },
  {
    "id": 39,
    "code": "P/dk",
    "nameKo": "어두운 보라",
    "nameEn": "dark Purple",
    "munsell": "5P 2/6",
    "l": 30.27,
    "a": 11.33,
    "b": -13.43,
    "commonKo": "가지색",
    "commonEn": "Eggplant"
  },
  {
    "id": 40,
    "code": "RP/dk",
    "nameKo": "어두운 자주",
    "nameEn": "dark Red Purple",
    "munsell": "5RP 2/6",
    "l": 31.16,
    "a": 15.11,
    "b": -4.88,
    "commonKo": "포도주색",
    "commonEn": "Wine"
  },
  {
    "id": 41,
    "code": "R/dl",
    "nameKo": "탁한 빨강",
    "nameEn": "dull Red",
    "munsell": "5R 4/4",
    "l": 45.06,
    "a": 16.81,
    "b": 5.9,
    "commonKo": "마룬색",
    "commonEn": "Maroon"
  },
  {
    "id": 42,
    "code": "YR/dl",
    "nameKo": "탁한 주황",
    "nameEn": "dull Yellow Red",
    "munsell": "5YR 4/4",
    "l": 44.92,
    "a": 15.21,
    "b": 15.92,
    "commonKo": "계피색",
    "commonEn": "Cinnamon"
  },
  {
    "id": 43,
    "code": "Y/dl",
    "nameKo": "탁한 노랑",
    "nameEn": "dull Yellow",
    "munsell": "5Y 4/4",
    "l": 44.43,
    "a": 3.18,
    "b": 19.18,
    "commonKo": "참기름색",
    "commonEn": "Sesame Oil"
  },
  {
    "id": 44,
    "code": "GY/dl",
    "nameKo": "탁한 연두",
    "nameEn": "dull Green Yellow",
    "munsell": "5GY 4/4",
    "l": 45.91,
    "a": -7.02,
    "b": 18.15,
    "commonKo": "쑥색",
    "commonEn": "Sage Green"
  },
  {
    "id": 45,
    "code": "G/dl",
    "nameKo": "탁한 초록",
    "nameEn": "dull Green",
    "munsell": "5G 4/4",
    "l": 46.12,
    "a": -15.24,
    "b": 6.31,
    "commonKo": "벽옥색",
    "commonEn": "Jasper Green"
  },
  {
    "id": 46,
    "code": "BG/dl",
    "nameKo": "탁한 청록",
    "nameEn": "dull Blue Green",
    "munsell": "5BG 4/4",
    "l": 46.72,
    "a": -17.04,
    "b": 2.21,
    "commonKo": "청동오리색",
    "commonEn": "Teal Green"
  },
  {
    "id": 47,
    "code": "B/dl",
    "nameKo": "탁한 파랑",
    "nameEn": "dull Blue",
    "munsell": "5B 4/4",
    "l": 46.4,
    "a": -12.76,
    "b": 11.05,
    "commonKo": "청옥색",
    "commonEn": "Light Blue"
  },
  {
    "id": 48,
    "code": "PB/dl",
    "nameKo": "탁한 남색",
    "nameEn": "dull Purple Blue",
    "munsell": "5PB 4/4",
    "l": 46.51,
    "a": -1.7,
    "b": 13.56,
    "commonKo": "연기색",
    "commonEn": "Smoke Blue"
  },
  {
    "id": 49,
    "code": "P/dl",
    "nameKo": "탁한 보라",
    "nameEn": "dull Purple",
    "munsell": "5P 4/4",
    "l": 46.39,
    "a": 8.41,
    "b": -11.74,
    "commonKo": "회보라",
    "commonEn": "Purple Gray"
  },
  {
    "id": 50,
    "code": "RP/dl",
    "nameKo": "탁한 자주",
    "nameEn": "dull Red Purple",
    "munsell": "5RP 4/4",
    "l": 45.68,
    "a": 15.58,
    "b": -1.57,
    "commonKo": "다알리아색",
    "commonEn": "Dahlia"
  },
  {
    "id": 51,
    "code": "R/sf",
    "nameKo": "흐린 빨강",
    "nameEn": "soft Red",
    "munsell": "5R 6/4",
    "l": 63.01,
    "a": 14.88,
    "b": 6.89,
    "commonKo": "계수나무색",
    "commonEn": "Cinnamon Tree"
  },
  {
    "id": 52,
    "code": "YR/sf",
    "nameKo": "흐린 주황",
    "nameEn": "soft Yellow Red",
    "munsell": "5YR 6/4",
    "l": 62.48,
    "a": 13.41,
    "b": 16.88,
    "commonKo": "쇠가죽색",
    "commonEn": "Cowhide"
  },
  {
    "id": 53,
    "code": "Y/sf",
    "nameKo": "흐린 노랑",
    "nameEn": "soft Yellow",
    "munsell": "5Y 6/4",
    "l": 62.93,
    "a": 2.42,
    "b": 23.13,
    "commonKo": "금향색",
    "commonEn": "Yellowish Brown"
  },
  {
    "id": 54,
    "code": "GY/sf",
    "nameKo": "흐린 연두",
    "nameEn": "soft Green Yellow",
    "munsell": "5GY 6/4",
    "l": 63.71,
    "a": -8.03,
    "b": 23.13,
    "commonKo": "회연두",
    "commonEn": "Citron Green"
  },
  {
    "id": 55,
    "code": "G/sf",
    "nameKo": "흐린 초록",
    "nameEn": "soft Green",
    "munsell": "5G 6/4",
    "l": 64.72,
    "a": -18.71,
    "b": 8.6,
    "commonKo": "파도색",
    "commonEn": "Surf Green"
  },
  {
    "id": 56,
    "code": "BG/sf",
    "nameKo": "흐린 청록",
    "nameEn": "soft Blue Green",
    "munsell": "5BG 6/4",
    "l": 64.33,
    "a": -18.54,
    "b": -0.88,
    "commonKo": "구리청자색",
    "commonEn": "Copper Green"
  },
  {
    "id": 57,
    "code": "B/sf",
    "nameKo": "흐린 파랑",
    "nameEn": "soft Blue",
    "munsell": "5B 6/4",
    "l": 64.42,
    "a": -12.7,
    "b": -9.01,
    "commonKo": "회청색",
    "commonEn": "Sax Blue"
  },
  {
    "id": 58,
    "code": "PB/sf",
    "nameKo": "흐린 남색",
    "nameEn": "soft Purple Blue",
    "munsell": "5PB 6/4",
    "l": 64.27,
    "a": -2.24,
    "b": -12.57,
    "commonKo": "오리엔트블루",
    "commonEn": "Orient Blue"
  },
  {
    "id": 59,
    "code": "P/sf",
    "nameKo": "흐린 보라",
    "nameEn": "soft Purple",
    "munsell": "5P 6/4",
    "l": 63.84,
    "a": 6.64,
    "b": -10.17,
    "commonKo": "담자색",
    "commonEn": "Light Purple"
  },
  {
    "id": 60,
    "code": "RP/sf",
    "nameKo": "흐린 자주",
    "nameEn": "soft Red Purple",
    "munsell": "5RP 6/4",
    "l": 63.61,
    "a": 13.76,
    "b": -1.21,
    "commonKo": "팥죽색",
    "commonEn": "Red Bean Soup Color"
  },
  {
    "id": 61,
    "code": "R/lt",
    "nameKo": "밝은 빨강",
    "nameEn": "light Red",
    "munsell": "5R 7/8",
    "l": 72.34,
    "a": 31.66,
    "b": 14.33,
    "commonKo": "산호색",
    "commonEn": "Coral"
  },
  {
    "id": 62,
    "code": "YR/lt",
    "nameKo": "밝은 주황",
    "nameEn": "light Yellow Red",
    "munsell": "5YR 7/8",
    "l": 71.72,
    "a": 24.72,
    "b": 34.78,
    "commonKo": "살구색",
    "commonEn": "Apricot"
  },
  {
    "id": 63,
    "code": "Y/lt",
    "nameKo": "밝은 노랑",
    "nameEn": "light Yellow",
    "munsell": "5Y 7/8",
    "l": 70.69,
    "a": 3.85,
    "b": 48.84,
    "commonKo": "감초색",
    "commonEn": "Apricot Yellow"
  },
  {
    "id": 64,
    "code": "GY/lt",
    "nameKo": "밝은 연두",
    "nameEn": "light Green Yellow",
    "munsell": "5GY 7/8",
    "l": 72.35,
    "a": -16.47,
    "b": 45.8,
    "commonKo": "배추색",
    "commonEn": "Chinese Cabbage Green"
  },
  {
    "id": 65,
    "code": "G/lt",
    "nameKo": "밝은 초록",
    "nameEn": "light Green",
    "munsell": "5G 7/8",
    "l": 74.24,
    "a": -36.78,
    "b": -0.08,
    "commonKo": "파도거품색",
    "commonEn": "Seafoam Green"
  },
  {
    "id": 66,
    "code": "BG/lt",
    "nameKo": "밝은 청록",
    "nameEn": "light Blue Green",
    "munsell": "5BG 7/8",
    "l": 73.89,
    "a": -36.17,
    "b": -0.08,
    "commonKo": "비취색",
    "commonEn": "Jade Green"
  },
  {
    "id": 67,
    "code": "B/lt",
    "nameKo": "밝은 파랑",
    "nameEn": "light Blue",
    "munsell": "5B 7/8",
    "l": 74.11,
    "a": -26.21,
    "b": -18.23,
    "commonKo": "물색",
    "commonEn": "Aqua Blue"
  },
  {
    "id": 68,
    "code": "PB/lt",
    "nameKo": "밝은 남색",
    "nameEn": "light Purple Blue",
    "munsell": "5PB 7/8",
    "l": 73.97,
    "a": -6.35,
    "b": -24.42,
    "commonKo": "하늘색",
    "commonEn": "Sky Blue"
  },
  {
    "id": 69,
    "code": "P/lt",
    "nameKo": "밝은 보라",
    "nameEn": "light Purple",
    "munsell": "5P 7/8",
    "l": 73.31,
    "a": -12.44,
    "b": -17.14,
    "commonKo": "무궁화색",
    "commonEn": "Rose of Sharon"
  },
  {
    "id": 70,
    "code": "RP/lt",
    "nameKo": "밝은 자주",
    "nameEn": "light Red Purple",
    "munsell": "5RP 7/8",
    "l": 72.96,
    "a": 28.09,
    "b": -1.71,
    "commonKo": "분홍",
    "commonEn": "Pink"
  },
  {
    "id": 71,
    "code": "R/pl",
    "nameKo": "연한 빨강",
    "nameEn": "pale Red",
    "munsell": "5R 8/4",
    "l": 81.12,
    "a": 14.92,
    "b": 8.07,
    "commonKo": "베이비핑크",
    "commonEn": "Baby Pink"
  },
  {
    "id": 72,
    "code": "YR/pl",
    "nameKo": "연한 주황",
    "nameEn": "pale Yellow Red",
    "munsell": "5YR 8/4",
    "l": 81.23,
    "a": 12.4,
    "b": 17.93,
    "commonKo": "계란색",
    "commonEn": "Eggshell"
  },
  {
    "id": 73,
    "code": "Y/pl",
    "nameKo": "연한 노랑",
    "nameEn": "pale Yellow",
    "munsell": "5Y 8/4",
    "l": 81.38,
    "a": 0.1,
    "b": 26.94,
    "commonKo": "두록색(豆綠)",
    "commonEn": "Soft Yellow"
  },
  {
    "id": 74,
    "code": "GY/pl",
    "nameKo": "연한 연두",
    "nameEn": "pale Green Yellow",
    "munsell": "5GY 8/4",
    "l": 81.95,
    "a": -10.03,
    "b": 27.35,
    "commonKo": "백연두",
    "commonEn": "Light Viridian Green"
  },
  {
    "id": 75,
    "code": "G/pl",
    "nameKo": "연한 초록",
    "nameEn": "pale Green",
    "munsell": "5G 8/4",
    "l": 81.97,
    "a": -19,
    "b": 10.44,
    "commonKo": "민트그린",
    "commonEn": "Mint Green"
  },
  {
    "id": 76,
    "code": "BG/pl",
    "nameKo": "연한 청록",
    "nameEn": "pale Blue Green",
    "munsell": "5BG 8/4",
    "l": 81.26,
    "a": -19.95,
    "b": 1.15,
    "commonKo": "빙산색",
    "commonEn": "Ice Green"
  },
  {
    "id": 77,
    "code": "B/pl",
    "nameKo": "연한 파랑",
    "nameEn": "pale Blue",
    "munsell": "5B 8/4",
    "l": 83.05,
    "a": -13.79,
    "b": -7.36,
    "commonKo": "파우더블루",
    "commonEn": "Powder Blue"
  },
  {
    "id": 78,
    "code": "PB/pl",
    "nameKo": "연한 남색",
    "nameEn": "pale Purple Blue",
    "munsell": "5PB 8/4",
    "l": 82.02,
    "a": -3.61,
    "b": -11.12,
    "commonKo": "베이비블루",
    "commonEn": "Baby Blue"
  },
  {
    "id": 79,
    "code": "P/pl",
    "nameKo": "연한 보라",
    "nameEn": "pale Purple",
    "munsell": "5P 8/4",
    "l": 82.39,
    "a": 5.46,
    "b": -60.72,
    "commonKo": "라일락색",
    "commonEn": "Lilac"
  },
  {
    "id": 80,
    "code": "RP/pl",
    "nameKo": "연한 자주",
    "nameEn": "pale Red Purple",
    "munsell": "5RP 8/4",
    "l": 81.34,
    "a": 12.26,
    "b": 0.32,
    "commonKo": "분홍난꽃색",
    "commonEn": "Orchid Pink"
  },
  {
    "id": 81,
    "code": "R/wh",
    "nameKo": "흰 빨강",
    "nameEn": "whitish Red",
    "munsell": "5R 9/2",
    "l": 91.47,
    "a": 4.97,
    "b": 5.6,
    "commonKo": "진주색",
    "commonEn": "Pearl White"
  },
  {
    "id": 82,
    "code": "YR/wh",
    "nameKo": "흰 주황",
    "nameEn": "whitish Yellow Red",
    "munsell": "5YR 9/2",
    "l": 90.14,
    "a": 7.24,
    "b": 10.56,
    "commonKo": "백상아색",
    "commonEn": "Ivory White"
  },
  {
    "id": 83,
    "code": "Y/wh",
    "nameKo": "흰 노랑",
    "nameEn": "whitish Yellow",
    "munsell": "5Y 9/2",
    "l": 90.41,
    "a": -0.31,
    "b": 15.71,
    "commonKo": "연미색",
    "commonEn": "Mayonnaise"
  },
  {
    "id": 84,
    "code": "GY/wh",
    "nameKo": "흰 연두",
    "nameEn": "whitish Green Yellow",
    "munsell": "5GY 9/2",
    "l": 90.53,
    "a": -5.17,
    "b": 15.55,
    "commonKo": "유백색",
    "commonEn": "Cream"
  },
  {
    "id": 85,
    "code": "G/wh",
    "nameKo": "흰 초록",
    "nameEn": "whitish Green",
    "munsell": "5G 9/2",
    "l": 91.61,
    "a": -11.78,
    "b": 7.79,
    "commonKo": "백록색",
    "commonEn": "Opal Green"
  },
  {
    "id": 86,
    "code": "BG/wh",
    "nameKo": "흰 청록",
    "nameEn": "whitish Blue Green",
    "munsell": "5BG 9/2",
    "l": 91.2,
    "a": -11.04,
    "b": 7.56,
    "commonKo": "백옥색",
    "commonEn": "French Gray"
  },
  {
    "id": 87,
    "code": "B/wh",
    "nameKo": "흰 파랑",
    "nameEn": "whitish Blue",
    "munsell": "5B 9/2",
    "l": 91.83,
    "a": -7.02,
    "b": -2.04,
    "commonKo": "박하색",
    "commonEn": "Mint"
  },
  {
    "id": 88,
    "code": "PB/wh",
    "nameKo": "흰 남색",
    "nameEn": "whitish Purple Blue",
    "munsell": "5PB 9/2",
    "l": 90.3,
    "a": -1.66,
    "b": -1.46,
    "commonKo": "청백색",
    "commonEn": "Burn Blue"
  },
  {
    "id": 89,
    "code": "P/wh",
    "nameKo": "흰 보라",
    "nameEn": "whitish Purple",
    "munsell": "5P 9/2",
    "l": 90.48,
    "a": 1.9,
    "b": -1.35,
    "commonKo": "백매화꽃색",
    "commonEn": "White Plum Blossom"
  },
  {
    "id": 90,
    "code": "RP/wh",
    "nameKo": "흰 자주",
    "nameEn": "whitish Red Purple",
    "munsell": "5RP 9/2",
    "l": 91.67,
    "a": 3.05,
    "b": 1.63,
    "commonKo": "벚꽃색",
    "commonEn": "Cherry Blossom"
  },
  {
    "id": 91,
    "code": "R/ltgy",
    "nameKo": "밝은회 빨강",
    "nameEn": "light grayish Red",
    "munsell": "5R 7/2",
    "l": 72.86,
    "a": 7.27,
    "b": 3.39,
    "commonKo": "로즈베이지",
    "commonEn": "Rose Beige"
  },
  {
    "id": 92,
    "code": "YR/ltgy",
    "nameKo": "밝은회 주황",
    "nameEn": "light grayish Yellow Red",
    "munsell": "5YR 7/2",
    "l": 73.21,
    "a": 7.55,
    "b": 8.95,
    "commonKo": "베이지",
    "commonEn": "Beige"
  },
  {
    "id": 93,
    "code": "Y/ltgy",
    "nameKo": "밝은회 노랑",
    "nameEn": "light grayish Yellow",
    "munsell": "5Y 7/2",
    "l": 72.41,
    "a": 0.76,
    "b": 13.9,
    "commonKo": "모래색",
    "commonEn": "Sand Gray"
  },
  {
    "id": 94,
    "code": "GY/ltgy",
    "nameKo": "밝은회 연두",
    "nameEn": "light grayish Green Yellow",
    "munsell": "5GY 7/2",
    "l": 71.58,
    "a": -5.87,
    "b": 13.03,
    "commonKo": "어린대나무색",
    "commonEn": "Grayish Green"
  },
  {
    "id": 95,
    "code": "G/ltgy",
    "nameKo": "밝은회 초록",
    "nameEn": "light grayish Green",
    "munsell": "5G 7/2",
    "l": 73.24,
    "a": -10.17,
    "b": 5.82,
    "commonKo": "녹회색",
    "commonEn": "Mist Green"
  },
  {
    "id": 96,
    "code": "BG/ltgy",
    "nameKo": "밝은회 청록",
    "nameEn": "light grayish Blue Green",
    "munsell": "5BG 7/2",
    "l": 73.27,
    "a": -10,
    "b": -0.22,
    "commonKo": "옥색",
    "commonEn": "Jade"
  },
  {
    "id": 97,
    "code": "B/ltgy",
    "nameKo": "밝은회 파랑",
    "nameEn": "light grayish Blue",
    "munsell": "5B 7/2",
    "l": 72.93,
    "a": -6.83,
    "b": -4.43,
    "commonKo": "안개색",
    "commonEn": "Fog Mist Gray"
  },
  {
    "id": 98,
    "code": "PB/ltgy",
    "nameKo": "밝은회 남색",
    "nameEn": "light grayish Purple Blue",
    "munsell": "5PB 7/2",
    "l": 73.47,
    "a": -1.4,
    "b": -4.95,
    "commonKo": "스카이그레이",
    "commonEn": "Sky Gray"
  },
  {
    "id": 99,
    "code": "P/ltgy",
    "nameKo": "밝은회 보라",
    "nameEn": "light grayish Purple",
    "munsell": "5P 7/2",
    "l": 73.33,
    "a": 3.13,
    "b": -40.02,
    "commonKo": "연보라",
    "commonEn": "Pale Purple"
  },
  {
    "id": 100,
    "code": "RP/ltgy",
    "nameKo": "밝은회 자주",
    "nameEn": "light grayish Red Purple",
    "munsell": "5RP 7/2",
    "l": 73.63,
    "a": 5.64,
    "b": -0.38,
    "commonKo": "밝은회자주",
    "commonEn": "Light Grayish Purple"
  },
  {
    "id": 101,
    "code": "R/gy",
    "nameKo": "회 빨강",
    "nameEn": "grayish Red",
    "munsell": "5R 5/2",
    "l": 54.5,
    "a": 7.88,
    "b": 2.97,
    "commonKo": "회자색",
    "commonEn": "Rose Gray"
  },
  {
    "id": 102,
    "code": "YR/gy",
    "nameKo": "회 주황",
    "nameEn": "grayish Yellow Red",
    "munsell": "5YR 5/2",
    "l": 54.34,
    "a": 7.21,
    "b": 8.1,
    "commonKo": "고엽색",
    "commonEn": "Dried Leaf"
  },
  {
    "id": 103,
    "code": "Y/gy",
    "nameKo": "회 노랑",
    "nameEn": "grayish Yellow",
    "munsell": "5Y 5/2",
    "l": 54.42,
    "a": 1.21,
    "b": 12.26,
    "commonKo": "카키색",
    "commonEn": "Khaki"
  },
  {
    "id": 104,
    "code": "GY/gy",
    "nameKo": "회 연두",
    "nameEn": "grayish Green Yellow",
    "munsell": "5GY 5/2",
    "l": 53.95,
    "a": -3.94,
    "b": 10,
    "commonKo": "해조색",
    "commonEn": "Sea Moss Green"
  },
  {
    "id": 105,
    "code": "G/gy",
    "nameKo": "회 초록",
    "nameEn": "grayish Green",
    "munsell": "5G 5/2",
    "l": 55.12,
    "a": -8.33,
    "b": 4.12,
    "commonKo": "회청자색",
    "commonEn": "Celadon Gray"
  },
  {
    "id": 106,
    "code": "BG/gy",
    "nameKo": "회 청록",
    "nameEn": "grayish Blue Green",
    "munsell": "5BG 5/2",
    "l": 55.43,
    "a": -8.07,
    "b": -0.64,
    "commonKo": "물보라색",
    "commonEn": "Spray Green"
  },
  {
    "id": 107,
    "code": "B/gy",
    "nameKo": "회 파랑",
    "nameEn": "grayish Blue",
    "munsell": "5B 5/2",
    "l": 55.26,
    "a": -6.1,
    "b": -5.35,
    "commonKo": "철회색",
    "commonEn": "Steel Gray"
  },
  {
    "id": 108,
    "code": "PB/gy",
    "nameKo": "회 남색",
    "nameEn": "grayish Purple Blue",
    "munsell": "5PB 5/2",
    "l": 55.35,
    "a": -0.63,
    "b": -6.36,
    "commonKo": "아연색",
    "commonEn": "Lead Gray"
  },
  {
    "id": 109,
    "code": "P/gy",
    "nameKo": "회 보라",
    "nameEn": "grayish Purple",
    "munsell": "5P 5/2",
    "l": 54.99,
    "a": 3.28,
    "b": -4.98,
    "commonKo": "라벤더그레이",
    "commonEn": "Lavender Gray"
  },
  {
    "id": 110,
    "code": "RP/gy",
    "nameKo": "회 자주",
    "nameEn": "grayish Red Purple",
    "munsell": "5RP 5/2",
    "l": 54.69,
    "a": 7.08,
    "b": -0.28,
    "commonKo": "회자주",
    "commonEn": "Grayish Purple"
  },
  {
    "id": 111,
    "code": "R/dkgy",
    "nameKo": "어두운회 빨강",
    "nameEn": "dark grayish Red",
    "munsell": "5R 3/2",
    "l": 37.9,
    "a": 8.66,
    "b": 3.02,
    "commonKo": "적토색",
    "commonEn": "Terra Rose"
  },
  {
    "id": 112,
    "code": "YR/dkgy",
    "nameKo": "어두운회 주황",
    "nameEn": "dark grayish Yellow Red",
    "munsell": "5YR 3/2",
    "l": 36.85,
    "a": 6.79,
    "b": 6.77,
    "commonKo": "흑갈색",
    "commonEn": "Blackish Brown"
  },
  {
    "id": 113,
    "code": "Y/dkgy",
    "nameKo": "어두운회 노랑",
    "nameEn": "dark grayish Yellow",
    "munsell": "5Y 3/2",
    "l": 37.13,
    "a": 1.3,
    "b": 7.72,
    "commonKo": "모카색",
    "commonEn": "Mocha"
  },
  {
    "id": 114,
    "code": "GY/dkgy",
    "nameKo": "어두운회 연두",
    "nameEn": "dark grayish Green Yellow",
    "munsell": "5GY 3/2",
    "l": 37.34,
    "a": -3.28,
    "b": 6.48,
    "commonKo": "미역색",
    "commonEn": "Seaweed Green"
  },
  {
    "id": 115,
    "code": "G/dkgy",
    "nameKo": "어두운회 초록",
    "nameEn": "dark grayish Green",
    "munsell": "5G 3/2",
    "l": 38.45,
    "a": -5.88,
    "b": 2.39,
    "commonKo": "진녹색",
    "commonEn": "Dark Ivy"
  },
  {
    "id": 116,
    "code": "BG/dkgy",
    "nameKo": "어두운회 청록",
    "nameEn": "dark grayish Blue Green",
    "munsell": "5BG 3/2",
    "l": 38.17,
    "a": -5.95,
    "b": -1.15,
    "commonKo": "흑록색",
    "commonEn": "Black Green"
  },
  {
    "id": 117,
    "code": "B/dkgy",
    "nameKo": "어두운회 파랑",
    "nameEn": "dark grayish Blue",
    "munsell": "5B 3/2",
    "l": 37.09,
    "a": -5.09,
    "b": -5.61,
    "commonKo": "어두운회블루",
    "commonEn": "Dark Grayish Blue"
  },
  {
    "id": 118,
    "code": "PB/dkgy",
    "nameKo": "어두운회 남색",
    "nameEn": "dark grayish Purple Blue",
    "munsell": "5PB 3/2",
    "l": 38.32,
    "a": -0.38,
    "b": -7.77,
    "commonKo": "프러시안블루",
    "commonEn": "Prussian Blue"
  },
  {
    "id": 119,
    "code": "P/dkgy",
    "nameKo": "어두운회 보라",
    "nameEn": "dark grayish Purple",
    "munsell": "5P 3/2",
    "l": 38.05,
    "a": 5.08,
    "b": -6.89,
    "commonKo": "검보라",
    "commonEn": "Black Purple"
  },
  {
    "id": 120,
    "code": "RP/dkgy",
    "nameKo": "어두운회 자주",
    "nameEn": "dark grayish Red Purple",
    "munsell": "5RP 3/2",
    "l": 37.63,
    "a": 8.36,
    "b": -1.63,
    "commonKo": "참새머리색",
    "commonEn": "Blackish Red Purple"
  },
  {
    "id": 121,
    "code": "R/bk",
    "nameKo": "검은 빨강",
    "nameEn": "blackish Red",
    "munsell": "5R 2/2",
    "l": 30.86,
    "a": 6.97,
    "b": 1.57,
    "commonKo": "간장색",
    "commonEn": "Soy Sause"
  },
  {
    "id": 122,
    "code": "YR/bk",
    "nameKo": "검은 주황",
    "nameEn": "blackish Yellow Red",
    "munsell": "5YR 2/2",
    "l": 30.46,
    "a": 6.65,
    "b": 5.14,
    "commonKo": "초콜릿색",
    "commonEn": "Chocolate"
  },
  {
    "id": 123,
    "code": "Y/bk",
    "nameKo": "검은 노랑",
    "nameEn": "blackish Yellow",
    "munsell": "5Y 2/2",
    "l": 31.48,
    "a": 2.61,
    "b": 6.34,
    "commonKo": "세피아",
    "commonEn": "Sepia"
  },
  {
    "id": 124,
    "code": "GY/bk",
    "nameKo": "검은 연두",
    "nameEn": "blackish Green Yellow",
    "munsell": "5GY 2/2",
    "l": 30.84,
    "a": -2.03,
    "b": 3.81,
    "commonKo": "김색",
    "commonEn": "Laver"
  },
  {
    "id": 125,
    "code": "G/bk",
    "nameKo": "검은 초록",
    "nameEn": "blackish Green",
    "munsell": "5G 2/2",
    "l": 31.3,
    "a": -4.33,
    "b": 1.44,
    "commonKo": "슬레이트그린",
    "commonEn": "Slate Green"
  },
  {
    "id": 126,
    "code": "BG/bk",
    "nameKo": "검은 청록",
    "nameEn": "blackish Blue Green",
    "munsell": "5BG 2/2",
    "l": 31.13,
    "a": -4.77,
    "b": -1.04,
    "commonKo": "흑록색",
    "commonEn": "Black Green"
  },
  {
    "id": 127,
    "code": "B/bk",
    "nameKo": "검은 파랑",
    "nameEn": "blackish Blue",
    "munsell": "5B 2/2",
    "l": 31.64,
    "a": -3.65,
    "b": -4.27,
    "commonKo": "심해색",
    "commonEn": "Marine Blue"
  },
  {
    "id": 128,
    "code": "PB/bk",
    "nameKo": "검은 남색",
    "nameEn": "blackish Purple Blue",
    "munsell": "5PB 2/2",
    "l": 31.43,
    "a": -0.35,
    "b": -6.37,
    "commonKo": "야암색",
    "commonEn": "Midnight Blue"
  },
  {
    "id": 129,
    "code": "P/bk",
    "nameKo": "검은 보라",
    "nameEn": "blackish Purple",
    "munsell": "5P 2/2",
    "l": 30.97,
    "a": 4.2,
    "b": -4.47,
    "commonKo": "흑자주",
    "commonEn": "Purplish Plack"
  },
  {
    "id": 130,
    "code": "RP/bk",
    "nameKo": "검은 자주",
    "nameEn": "blackish Red Purple",
    "munsell": "5RP 2/2",
    "l": 31.02,
    "a": 6.63,
    "b": -2.18,
    "commonKo": "검자주색",
    "commonEn": "Blackish Red Purple"
  }
];
